# Generated by Django 6.0.2 on 2026-03-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_inquiry_options_remove_inquiry_seeker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, help_text='Full street address', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Sq Ft'), ('sqyard', 'Sq Yards'), ('sqmeter', 'Sq Meter'), ('acres', 'Acres'), ('marlas', 'Marlas'), ('cents', 'Cents')], default='sqft', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk',
            field=models.CharField(blank=True, choices=[('1rk', '1 RK'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk+', '5 BHK+')], max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('new_launch', 'New Launch'), ('under_construction', 'Under Construction'), ('ready_to_move', 'Ready To Move')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='max_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('builder', 'Builder'), ('dealer', 'Dealer'), ('featured_dealer', 'Featured Dealer')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_tenants',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('single_man', 'Single Man'), ('single_woman', 'Single Woman'), ('company_lease', 'Company Lease'), ('any', 'Any')], max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 Years'), ('1-5', '1-5 Years'), ('5-10', '5-10 Years'), ('10-20', '10-20 Years'), ('20+', '20+ Years')], max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('resale', 'Resale'), ('new_booking', 'New Booking')], max_length=15),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
