# Generated by Django 6.0.2 on 2026-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_address_property_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryreply',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
