# Generated by Django 6.0.4 on 2026-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('studio', '1 RK / Studio Apartment'), ('office', 'Office'), ('retail', 'Retail / Shop'), ('plot', 'Plot / Land'), ('storage', 'Storage / Warehouse'), ('work_live_studio', 'Work-Live Studio')], max_length=20),
        ),
    ]
