# Generated by Django 6.0.4 on 2026-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryreply',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
