# Generated by Django 6.0.4 on 2026-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_inquiryreply_is_rented_property_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.CharField(blank=True, help_text='e.g. 3, Ground, Basement', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.CharField(blank=True, choices=[('marble', 'Marble'), ('vitrified_tiles', 'Vitrified Tiles'), ('ceramic_tiles', 'Ceramic Tiles'), ('wooden', 'Wooden'), ('granite', 'Granite'), ('mosaic', 'Mosaic'), ('normal_tiles', 'Normal Tiles')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='key_facilities',
            field=models.TextField(blank=True, help_text='Comma-separated facilities, e.g. 24hr Security, CCTV'),
        ),
        migrations.AddField(
            model_name='property',
            name='key_highlights',
            field=models.TextField(blank=True, help_text='Why should someone consider this property?'),
        ),
        migrations.AddField(
            model_name='property',
            name='overlooking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_common_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_for',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_meals_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_notice_period',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='property_ownership',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('cooperative', 'Co-operative Society'), ('power_of_attorney', 'Power of Attorney')], max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='RERA ID'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('pg_owner', 'PG Owner'), ('owner', 'Owner'), ('builder', 'Builder'), ('dealer', 'Dealer')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('new_property', 'New Property'), ('resale', 'Resale')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='vastu_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, choices=[('borewell', 'Borewell'), ('municipal', 'Municipal Corporation'), ('both', 'Both (Borewell + Municipal)')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='width_of_facing_road',
            field=models.CharField(blank=True, help_text='e.g. 30 ft, 9 metres', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sell', 'For Sale'), ('pg', 'PG / Co-living')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('pg', 'PG / Co-living')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat_apartment', 'Flat / Apartment'), ('independent_house_villa', 'Independent House / Villa'), ('builder_floor', 'Independent / Builder Floor'), ('plot_land_res', 'Plot / Land'), ('studio_1rk', '1 RK / Studio Apartment'), ('farmhouse', 'Farmhouse'), ('office', 'Office Space'), ('retail', 'Retail / Shop'), ('plot_land_com', 'Commercial Plot / Land'), ('storage', 'Storage / Warehouse'), ('dance_studio', 'Dance / Fitness Studio'), ('coworking', 'Co-working Space'), ('showroom', 'Showroom'), ('restaurant_cafe', 'Restaurant / Café'), ('pg_hostel', 'PG / Hostel')], max_length=30),
        ),
    ]
